#theme: jekyll-theme-cayman

name: Firas S Midani
title: firas midani
email: firas.midani@duke.edu

# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty
date_format: "%Y-%m-%d"


# Third-party services
# just leave someone empty to disable it
google_analytics:
disqus_shortname:
gems:
  - jekyll-seo-tag
