#theme: jekyll-theme-cayman

name: Firas S Midani
title: firas midani
email: firas.midani@bcm.edu

# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty
date_format: "%Y-%m-%d"
syntax_highlighter: Pygments

# Third-party services
# just leave someone empty to disable it
google_analytics:
disqus_shortname:
